name: lg_controller
description: Controller application for the LG Screen.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bloc: ^0.14.0
  flutter_bloc: ^0.14.0
  page_transition: '^1.1.0'
  equatable: ^0.2.0
  shared_preferences: ^0.4.3
  googleapis: 'any'
  googleapis_auth: '0.2.7'
  path_provider: '^0.4.0'
  sqflite: '^1.1.0'
  google_maps_flutter: '^0.5.16'
  flutter_google_places: '^0.2.3'
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: "^0.7.2"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "image_assets/AppLogo.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - image_assets/


